<style type="text/css">
/*==========================================
*
*           Universal Styling
*
===========================================*/

* {
  margin: 0;
  padding: 0;
  font-family: 'Helvetica Neue', sans-serif;
  text-decoration: none;
}

@font-face{
  font-family: 'Helvetica Neue';
  src: url('../fonts/helvetica-neue.ttf') format('truetype');
}

/*==========================================
*
*             Body Content
*
===========================================*/

body {
  background-color: #000000;
}

.text-section {
  margin: 0 auto;
  max-width: 500px;
  margin-top: 350px;
  text-align: center;
}

h1 {
  font-family: 'Helvetica Neue', sans-serif;
  font-weight: bold;
  letter-spacing: 3px;
  font-size: 18px;
  color: #ffffff;
}

h2 {
  font-family: 'Helvetica Neue', sans-serif;
  font-weight: lighter;
  letter-spacing: 3px;
  font-size: 14px;
  color: #ffffff;
}

h4 {
  color: #ffffff;
  font-weight: normal;
  letter-spacing: 3px;
}

.home {
  background-color: transparent;
  border: 1px solid #ffffff;
  padding: 15px 32px;
  text-align: center;
  display: inline-block;
  margin-top: 20px;
  color: #ffffff;
}

.home:hover {
  transition: .3s;
  text-decoration: none;
  opacity: 50%;
}

</style>

<body>
  <section class="text-section">
    <h1>Thank you for your inquiry.</h1>
    <h2>Thanks for your interest. we have received your message, and we will be in touch shortly.</h2>
    <br>
    <h2>Form processor provided by <a href="http://www.inventpartners.com">Invent Partners web design York</a>.</h2>
  </section>
</body>
